
/******************************************************************************
*
*   FILE
*   ----
*   subscriptionResult.c
*
*   History
*   -------
*   2018-01-23   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_opcuaSubscription
#define OV_COMPILE_LIBRARY_opcuaSubscription
#endif


#include "opcuaSubscription.h"
#include "ov_association.h"

#include "ov_macros.h"

OV_IMPL_LINK(opcuaSubscription_subscriptionResult)
OV_IMPL_UNLINK(opcuaSubscription_subscriptionResult)
OV_IMPL_GETACCESS(opcuaSubscription_subscriptionResult)

